@startuml

left to right direction
skinparam packageStyle rectangle

actor Usuario

rectangle "Gestión de Restaurantes" {
    usecase "Agregar Restaurante" as UC1
    usecase "Eliminar Restaurante" as UC2
}

Usuario --> UC1
Usuario --> UC2
UC1 --> ControladorRestaurantes
UC2 --> ControladorRestaurantes

@enduml
