@startuml

left to right direction
skinparam packageStyle rectangle

actor Cliente
actor Administrador

rectangle "Gestión de Restaurantes" {
    usecase "Mostrar Detalles del Restaurante" as UC1
    usecase "Agregar Restaurante" as UC2
    usecase "Eliminar Restaurante" as UC3
}

rectangle "Gestión de Reservas" {
    usecase "Realizar Reserva" as UC4
}

rectangle "Gestión de Notificaciones" {
    usecase "Notificar Cliente" as UC5
}

Cliente --> UC4
Administrador --> UC2
Administrador --> UC3
UC2 --> UC1
UC3 --> UC1
UC5 --> Cliente

@enduml
